Update structs and marshal for component tag and attr
mc2soft/mpd pull request #6
Opened 2020-09-07 15:11 UTC by maxkur

Обновлены модули и Go.
Обновлены структуры.
Добавлены недостающие поля.
Добавлен маршалинг составных тегов и атрибутов типа `cenc:pssh`

2020-09-08 13:39 UTC, lcd1232 approved these changes

2020-09-08 16:09 UTC, avhitrov requested changes
Экономим время и память

2020-09-08 16:09 UTC, avhitrov commented on mpd.go
> +	}
```suggestion
	}
       asm := make([]*adaptationSetMarshal, 0, len(as))
```

2020-09-08 16:09 UTC, avhitrov commented on mpd.go
> +func modifyRepresentations(rs []Representation) (rsm []representationMarshal) {
```suggestion
func modifyRepresentations(rs []Representation) []representationMarshal {
     rsm := make([]representationMarshal, 0, len(rs))
```

2020-09-08 16:09 UTC, avhitrov commented on mpd.go
> +func copySegmentTimelineS(st []SegmentTimelineS) (stm []SegmentTimelineS) {
```suggestion
func copySegmentTimelineS(st []SegmentTimelineS) []SegmentTimelineS {
    stm := make([]SegmentTimelineS, 0, len(st))
```

2020-09-08 16:09 UTC, avhitrov commented on mpd.go
> +func copySegmentTimelineS(st []SegmentTimelineS) (stm []SegmentTimelineS) {
И дальше по коду

2020-09-08 23:46 UTC, avhitrov approved these changes

2020-09-09 07:17 UTC, bikbah approved these changes

2020-09-09 07:17 UTC, bikbah commented on .travis.yml
>    - 1.13.x
удаляем

2020-09-09 07:17 UTC, bikbah commented on utils/copyjob.go
> +package utils
package copyobj

2020-09-09 07:30 UTC, lcd1232 commented on .travis.yml
>    - 1.13.x
Зачем удалять? Он же работает - https://travis-ci.org/mc2soft/mpd

2020-09-09 08:30 UTC, merged